# Site settings
title:          Chenyl
description:    "Minimal Jekyll theme for storytellers"
url:            "https://chenylvia.github.io/"

# Google Analytics
google_analytics: UA—XXXXXXXX-X

# Author
author:
  name:         Chenyl
  url:          https://chenylvia.github.io/
  email:        yulin.chen.sc@gmail.com

# Build settings
markdown:       kramdown
include:
  - _pages

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5

# Excludes
exclude: [ Gemfile, Gemfile.lock, tale.gemspec ]

# Disqus (Set to your disqus id)
disqus:         jekyll-tale
